Add Cache-Control
sindresorhus/gh-latest-repos pull request #9
Opened 2018-01-16 15:32 UTC by willnode

Add HTTP Header `cache-control` so that browsers can cache requests for short time, thus saving bandwidth in the long term.

Also adds CACHE_MAX_AGE optional environment variable in case someone wish to modify that.

2018-01-16 15:55 UTC, willnode commented
whoa, the test fail?

2018-01-16 16:09 UTC, SamVerschueren requested changes

2018-01-16 16:09 UTC, SamVerschueren commented on index.js
> +	response.setHeader("cache-control", cache)
Single quotes

2018-01-16 16:09 UTC, SamVerschueren commented on index.js
> +const cache = "max-age=" + (process.env.CACHE_MAX_AGE || 300);
Template string

2018-01-16 22:02 UTC, sindresorhus commented
You could add ETag to, which has much more effect, especially since the repos are only updates once a day.

https://github.com/jshttp/etag

2018-01-16 23:16 UTC, willnode commented on index.js
> +	response.setHeader("cache-control", cache)
done

2018-01-16 23:17 UTC, willnode commented on index.js
> +const cache = "max-age=" + (process.env.CACHE_MAX_AGE || 300);
done (on etag commit)

2018-02-15 05:10 UTC, merged

2018-02-15 05:10 UTC, sindresorhus commented
Looks good. Thank you :)